--- 
abstract: "\xE3\x82\xAE\xE3\x83\xAD\xE3\x83\x83\xE3\x83\x9D\xE3\x83\xB3\xE3\x81\xAB\xE3\x83\x86\xE3\x83\x83\xE3\x83\x9A\xE3\x83\xB3\xE3\x81\xA7\xE3\x83\x90\xE3\x83\x9F\xE3\x81\xA3\xE3\x81\x9F"
author: 
  - Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-Shukugawa-Atom
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 0
  Text::MeCab: 0.20007
version: 0.00001
