custom_words:
# 変換順序が影響するので、美しくないですがここは配列の中にさらに配列
# を記述してください
    - ['急ぎで|急いでる?', '巻きで']
    - ['小飼弾|(?i)dankogai|(?i)kogaidan', 'ガイダンコ']
    - ['銀座', 'ザギン']
    - ['別に', 'ジリサワゴネタ']
    - ['予約した', 'バミった']
    - ['[2２][4４]時|午前[0０]時', 'テッペン']
    - ['巨乳|胸(?:の|が)(大きい|でかい|デカイ)', 'パイオツカイデー']
    - ['女性|女の人|お姉さん|おねーさん', 'チャンネー']
    - ['お?(?:ばあ|婆)さん', 'チャンバー']
    - ['(?:おおきい|大きい)(?:のか?|か)?', 'カイデー']
    - ['赤ずきんちゃん', 'ズキアカのチャンネー']
    - ['屁', 'エーヘー']
    - ['火', 'イーヒー']
    - ['金槌', 'ナグリ']
    - ['抱き合わせ', 'バーター']
    - ['編集', 'つまむ']
    - ['斜め', 'ヤオヤ']
    - ['片付け|かたづけ|どける|取り除く|除く', 'わらう']
    - ['どけて|取って', 'わらって']
    - ['片付ける|かたづける', 'ばらす']
    - ['中止|取り消し|とりけし', 'ばらし']
    - ['片付けて|かたづけて', 'ばらして']
    - ['片付けた|かたづけた', 'ばらした']
    - ['キャンセル|解除|解散', 'ばらし']
    - ['決定|決める|決断|確定', 'フィックス']
    - ['固定', '板付き']
    - ['上から', 'フカン']
    - ['下から', 'アオリ']
    - ['右側', 'かみ手']
    - ['左側', 'しも手']
    - ['一杯まで', 'ドンまで']
    - ['ライブラリ|既存', '有りもの']
    - ['アングル', '角度']
    - ['越し', 'ナメ']
    - ['アシスタント', 'アシ']
    - ['出来た|完成した|出来上がった|できた|できあがった|出来あがった', 'パケった']
    - ['きっかけ', 'キュー']
    - ['逆に|反対に', 'テレコに']
    - ['入れ替える', 'テレコする']
    - ['傾ける', '八百屋する']
    - ['傾けて', '八百屋して']
    - ['広い|ひろい', 'ワイド']
    - ['晴れ|快晴|青空', 'ピーカン']
    - ['遅れている|遅れる', 'おし']
    - ['早く|急い|急ぎ', 'まき']
    - ['回す', '時計する']
    - ['回して', '時計して']
    - ['約束|予約', 'アポ']
    - ['乳首', 'ビーチク']
    - ['撮影', '撮り']
    - ['駄目|ダメ|だめ', 'ＮＧ']
    - ['交換', 'バーター']
    - ['横切る|通り過ぎる', 'ワイプする']
    - ['横切った|通り過ぎた', 'ワイプした']
    - ['時間|長さ', '尺']
    - ['用意する|準備する', 'しこむ']
    - ['フジテレビ', 'CX']
    - ['ニッポン放送', 'LF']
    - ['テレビ東京', 'TX']
    - ['文化放送', 'QR']
    - ['日本テレビ', '日テレ']
    - ['食費', 'アゴ' ]
    - ['交通費', 'アシ' ]
    - [ '(?!照明を)(?:当|あ)てる', 'うつ' ]
    - [ '収容', 'キャパ' ]
    - [ 'ガムテープ', 'ガバチョ' ]
    - [ '納期|(締め|〆)切り', 'ケツカッチン' ]
    - [ '見上げ(?!る|た)', 'あおり' ]
    - [ '予備', '押さえ' ]
    - [ '食べ物', '消えもの' ]
